name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Podman
      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build the Podman image
      - name: Build Podman image
        run: |
          podman build -t ${{ secrets.DOCKER_USERNAME }}/ecommerce:$GITHUB_SHA .
          podman tag ${{ secrets.DOCKER_USERNAME }}/ecommerce:$GITHUB_SHA ${{ secrets.DOCKER_USERNAME }}/ecommerce:latest

      - name: Push image to Docker Hub
        run: |
          podman push ${{ secrets.DOCKER_USERNAME }}/ecommerce:$GITHUB_SHA
          podman push ${{ secrets.DOCKER_USERNAME }}/ecommerce:latest

      #Deploy to Vercel
      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
